### ISSUE TITLE
与 vue3 的不同之处，或者更优之处在什么地方呢？

### ISSUE THREAD

**Issue by troyzhxu** [anuoua/unis#1]

**Comment by anuoua** [comment]
我在[这篇文章](https://juejin.cn/post/7042954046948245541)中有提到

有以下几点：

- 使用 Composition API，Vue 3 用户将会非常熟悉。
- 使用 JSX ，兼容 React 用法，Typescript 支持非常友好。
- 只有函数形态的组件，和 React 函数组件接近。
- 只运行一次（相比hooks）。
- 组件级别的精确更新。
- 简单易用，精简了 Vue 中过滤器、指令等概念，难度介于 Vue 和 React 之间，找到一个很好的平衡点。

可以理解成一个 Composition API 版的 React，或者改版的 Vue 3。
