### ISSUE TITLE
跟class的区别？

### ISSUE THREAD

**Issue by javaxiu** [anuoua/unis#5]
返回一个 render 函数，相当于 class component 里的 render 方法，本质上，class 组件也没有每次渲染就都全都跑一遍的问题，useProps 都在 this.props 上，甚至还能拿到 prevProps，这通优化下来，不知道会不会有一种「诶？class 组件好像就挺好」的感觉？

把那些 hooks(FC组件的优势) 都加回来，性能是否还有很大优化的效果呢？

**Comment by anuoua** [comment]
> 返回一个 render 函数，相当于 class component 里的 render 方法，本质上，class 组件也没有每次渲染就都全都跑一遍的问题，useProps 都在 this.props 上，甚至还能拿到 prevProps，这通优化下来，不知道会不会有一种「诶？class 组件好像就挺好」的感觉？
> 
> 把那些 hooks(FC组件的优势) 都加回来，性能是否还有很大优化的效果呢？

很有意思的说法，class 组件的最大问题就是复用、抽象、类型约束都不够易用，React 转移到 FC 后，前面的问题可以说已经解决。

而 Unis 想要解决的问题并不是 class 的问题，而是 React FC 的问题，从 React class -> React FC -> Unis 都是在前者优势上发展而来的，所以不可能退回去设计 class component。

至于性能，其实社区也有不少优秀的实践案例，只不过我看了几个都会限制 jsx 的自由发挥，看取舍，传统方案的虚拟DOM前端框架基本就这样了。
